using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace CharismaSDK.Events
{
    public enum MessageType
    {
        character,
        media,
        panel
    }

    public class MessageEvent
    {
        /// <summary>
        /// Message generated by Charisma.
        /// </summary>
        [JsonConstructor]
        public MessageEvent(int conversationId, MessageType type, Message message, bool endStory,
            bool tapToContinue, CharacterMood[] characterMoods, Memory[] memories, string eventId, ulong timestamp,
            Impacts impacts)
        {
            this.ConversationId = conversationId;
            this.MessageType = type;
            this.Message = message;
            this.EndStory = endStory;
            this.CharacterMoods = characterMoods;
            this.TapToContinue = tapToContinue;
            this.Memories = memories;
            this.EventId = long.Parse(eventId);
            this.Timestamp = timestamp;
        }

        /// <summary>
        /// The conversation id of the message.
        /// </summary>
        public int ConversationId { get; }

        /// <summary>
        /// The type of this message.
        /// </summary>
        public MessageType MessageType { get; }

        /// <summary>
        /// Contents of the message.
        /// </summary>
        public Message Message { get; }

        /// <summary>
        /// True if the node this message was generated from has "End Story" activated.
        /// </summary>
        public bool EndStory { get; }

        /// <summary>
        /// True if the node this message was generate from has "Tap To Continue" activated.
        /// </summary>
        public bool TapToContinue { get; }

        /// <summary>
        /// List of character moods which has changed on this node.
        /// </summary>
        public CharacterMood[] CharacterMoods { get; }

        /// <summary>
        /// List of memories which has changed since the last character node.
        /// </summary>
        public Memory[] Memories { get; }

        public long EventId { get; }
        public ulong Timestamp { get; }
    }

    public class Impacts
    {
        [JsonConstructor]
        public Impacts(int[] id, string impact)
        {
            Id = id;
            Impact = impact;
        }

        public int[] Id { get; }
        public string Impact { get; }
    }

    /// <summary>
    /// Contains data related to a characters response such as, text, audio etc.
    /// </summary>
    public class Message
    {
        [JsonConstructor]
        public Message(string text, Character character, Speech speech,
            Dictionary<string, string> metadata)
        {
            this.Character = character;
            this.Text = text;
            this.Speech = speech;
            this.Metadata = metadata;
        }

        /// <summary>
        /// The text of the response.
        /// </summary>
        public string Text { get; }

        /// <summary>
        /// The character that spoke / said something.
        /// </summary>
        public Character Character { get; }

        /// <summary>
        /// The audio information generated by the speech on this node
        /// </summary>
        public Speech Speech { get; }

        /// <summary>
        /// Metadata attached to this node.
        /// </summary>
        public Dictionary<string, string> Metadata { get; }
    }

    public class Character
    {
        [JsonConstructor]
        public Character(int id, string name, string avatar)
        {
            this.Id = id;
            this.Name = name;
            this.Avatar = avatar;
        }

        /// <summary>
        /// Id of this character.
        /// </summary>
        public int Id { get; }

        public string Name { get; }

        /// <summary>
        /// Url string of this characters avatar.
        /// </summary>
        public string Avatar { get; }
    }

    public class CharacterMood
    {
        [JsonConstructor]
        public CharacterMood(int id, string name, Mood mood)
        {
            this.Id = id;
            this.Name = name;
            this.Mood = mood;
        }

        public int Id { get; }
        public string Name { get; }

        /// <summary>
        /// Contains the mood of this character.
        /// </summary>
        public Mood Mood { get; }
    }

    public class Mood
    {
        public int anger { get; set; }
        public int trust { get; set; }
        public int patience { get; set; }
        public int happiness { get; set; }
        public int fearlessness { get; set; }

        [JsonConstructor]
        public Mood(int happiness, int anger, int trust, int patience, int fearlessness)
        {
            this.happiness = happiness;
            this.anger = anger;
            this.trust = trust;
            this.patience = patience;
            this.fearlessness = fearlessness;
        }
    }

    [Serializable]
    public class Memory
    {
        public string memoryRecallValue;
        public string saveValue;

        private readonly int _id;

        [JsonConstructor]
        public Memory(int id, string recallValue, string saveValue)
        {
            this._id = id;
            this.memoryRecallValue = recallValue;
            this.saveValue = saveValue;
        }

        /// <summary>
        /// Id of this memory
        /// </summary>
        public int Id => _id;

        /// <summary>
        /// Recall value of this memory
        /// </summary>
        public string MemoryRecallValue => memoryRecallValue;

        /// <summary>
        /// Save value of this memory
        /// </summary>
        public string SaveValue
        {
            get => saveValue;
            set => saveValue = value;
        }
    }
}
