using Newtonsoft.Json;

namespace CharismaSDK
{   
    public enum CharismaMessageType
    {
        character,
        media
    }
    
    public class Response
    {
        /// <summary>
        /// Response generated by Charisma.
        /// </summary>
        [JsonConstructor]
        public Response(int conversationId, CharismaMessageType messageType, ResponseMessage message, bool endStory, bool tapToContinue, CharacterMood[] characterMoods, Memory[] memories)
        {
            this.ConversationId = conversationId;
            this.CharismaMessageType = messageType;
            this.Message = message;
            this.EndStory = endStory;
            this.CharacterMoods = characterMoods;
            this.TapToContinue = tapToContinue;
            this.Memories = memories;
        }

        /// <summary>
        /// The conversation id of the response.
        /// </summary>
        public int ConversationId { get; }
        
        /// <summary>
        /// The type of this message.
        /// </summary>
        public CharismaMessageType CharismaMessageType { get; }
        
        /// <summary>
        /// Contents of the message.
        /// </summary>
        public ResponseMessage Message { get; }
        
        /// <summary>
        /// True if the node this response was generated from has "End Story" activated.
        /// </summary>
        public bool EndStory { get; }
        
        /// <summary>
        /// True if the node this response was generate from has "Tap To Continue" activated.
        /// </summary>
        public bool TapToContinue { get; }
        
        /// <summary>
        /// List of character moods which has changed on this node.
        /// </summary>
        public CharacterMood[] CharacterMoods { get; }
        
        /// <summary>
        /// List of memories which has changed since the last character node.
        /// </summary>
        public Memory[] Memories { get; }
    }
}
