using System.Collections.Generic;
using CharismaPlugin;
using Newtonsoft.Json;

namespace CharismaSDK
{
    /// <summary>
    /// Contains data related to a characters response such as, text, audio etc.
    /// </summary>
    public class ResponseMessage
    {
        [JsonConstructor]
        public ResponseMessage(string text, Character character, Speech speech,
            Dictionary<string, string> metadata)
        {
            this.Character = character;
            this.Text = text;
            this.Speech = speech;
            this.Metadata = metadata;
        }

        /// <summary>
        /// The text of the response.
        /// </summary>
        public string Text { get; }
        
        /// <summary>
        /// The character that spoke / said something.
        /// </summary>
        public Character Character { get; }
        
        /// <summary>
        /// The audio information generated by the speech on this node
        /// </summary>
        public Speech Speech { get; }
        
        /// <summary>
        /// Metadata attached to this node.
        /// </summary>
        public Dictionary<string, string> Metadata { get; }
    }
}
